#!/bin/bash

dirname=$(dirname "$0")

# read settings
source $dirname/settings.conf

repodir="/srv/git"
trashdir="/srv/git/trash"
linkdir="/home/git"

################################################################################

echo "${GITSERVER_MSG_WELCOME}"
echo ""

# show repos and sizes
source "$dirname/list"

echo ""
echo "Available commands:"
echo ""
echo "    help      Show this help"
echo "    list      List repositories"
echo "    new       Create new repository"
echo "    delete    Delete repository"
echo "    undelete  Undo deleted repository"
echo "    exit      Exit session"
echo ""

