#!/bin/bash

dirname=$(dirname "$0")

# read settings
source $dirname/settings.conf

repodir="/srv/git"
trashdir="/srv/git/trash"
linkdir="/home/git"

echo "Git repositories:"
echo ""
gdu $repodir -n --ignore-dirs $trashdir 
