#!/bin/bash

#export PATH=$PATH:~/.gem/ruby/2.6.0/bin

dirname=$(dirname "$0")

repodir="/srv/git"
linkdir="/home/git"

# test if at least 1 argument 
if [ -z "$1" ]; then
    echo "Usage: new <name of new repository>"
    exit
fi

# remove unwanted parent directories
reponame=$(basename "$1")
#echo $reponame

# remove .git extension (we'll add it)
reponame="${reponame%*.git}"
#echo $reponame

# transliterate to ascii
reponame=$(echo "$reponame" | iconv -f utf-8 -t ascii//translit)
#echo $reponame

# remove strange characters: everything excepty letters, numbers, _ and -
reponame="${reponame//[^[:alnum:] _-]/}"
#echo $reponame

# convert spaces to dashes
reponame="${reponame// /-}"
#echo $reponame

repotarget="$repodir/$reponame.git"
#echo $repotarget


# test if repo exist
if test -d "$repotarget"; then 
  echo "Repository "'"'"$reponame"'"'" exists - exiting."
  exit
fi 


# create destination for $reponame if it does not exists
#mkdir "$repodir"
echo "Setting up Git repository..."
#echo "mkdir $repotarget"
#echo "cd $repotarget"
#echo "git init --bare"
mkdir "$repotarget"
cd "$repotarget"
git init --bare --initial-branch=main

# create symlink for better URL's
linktarget="$linkdir/$reponame.git"
#echo "ln -s $repotarget $linktarget"
#echo ""
#echo ""
#echo ""
#echo ""
ln -s "$repotarget" "$linktarget"

# finished.
#echo "Sucessfully created repository "'"'"$reponame"'"'
echo ""
echo ""
echo "Now, on your local computer:"
echo ""
echo "  $ cd <local project directory>"
echo "  $ git init"
echo "  $ git add <files>"
echo "  $ git commit"
echo "  $ git remote add origin git@<your domain>:$reponame.git"
echo "  $ git push origin main"
echo ""
echo ""

#~~~bash
#$ mkdir /srv/git/reponame.git
#$ cd /home/git
#$ ln -s /srv/git/reponame.git
#$ cd reponame.git
#$ git init --bare
#~~~
