#!/bin/sh

dirname=$(dirname "$0")

# read settings
source $dirname/settings.conf

echo ""

echo "Hi 🙋"
echo ""

echo "You are authenticated, but I do not grant you interactive shell access 😂 😂 😂"
echo ""

echo "Peace ☮️"
echo ""

exit 128
